services:

  postgres:
    image: postgres:17
    container_name: tradepilot-postgres

    environment:
      POSTGRES_DB: tradepilot
      POSTGRES_USER: tradepilot
      POSTGRES_PASSWORD: tradepilot123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: tradepilot-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: