services:

  postgres:
    image: postgres:17
    container_name: tradepilot-postgres

    environment:
      POSTGRES_DB: tradepilot
      POSTGRES_USER: tradepilot
      POSTGRES_PASSWORD: tradepilot123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: